### ISSUE TITLE
requirements are outdated

### ISSUE THREAD

**Issue by lancelote** [ErnstHaagsman/car-behave#1]
Should include `behave` and `PyHamcrest`

**Comment by ErnstHaagsman** [comment]
Fixed PyHamcrest in d6988e3

I had to add behave to the requirements.txt as a Git repo due to https://github.com/behave/behave/issues/536. Did it not install correctly for you?

**Comment by lancelote** [comment]
Ah, I see, works fine, thank you! PyCharm doesn't suggest to auto-install `behave` from requirements if git link is used. Will ask Semyon if we can do something with it.
